import os
import asyncio
import logging
import tempfile
import subprocess
import json
from typing import Optional, Dict, Any, AsyncGenerator
import numpy as np
import soundfile as sf
from piper import PiperVoice
import io

logger = logging.getLogger(__name__)

class TTSService:
    """Text-to-Speech service using Piper TTS with en_US-libritts-high model"""
    
    def __init__(self):
        self.voice = None
        self.is_available = False
        self.sample_rate = 22050  # Piper default sample rate
        self.model_path = None
        self.config_path = None
        
        # Model paths - will be downloaded at build time
        self.model_dir = os.getenv("MODEL_PATH", "/app/models")
        self.voice_name = "en_US-libritts-high"
        
        # Streaming state
        self.is_speaking = False
        self.should_stop = False
        
    async def initialize(self):
        """Initialize the Piper TTS model"""
        try:
            logger.info("Initializing Piper TTS with en_US-libritts-high model...")
            
            # Set model and config paths
            self.model_path = os.path.join(self.model_dir, f"{self.voice_name}.onnx")
            self.config_path = os.path.join(self.model_dir, f"{self.voice_name}.onnx.json")
            
            # Check if model files exist
            if not os.path.exists(self.model_path):
                raise Exception(f"Model file not found: {self.model_path}")
            if not os.path.exists(self.config_path):
                raise Exception(f"Config file not found: {self.config_path}")
            
            # Load the voice
            def load_voice():
                return PiperVoice.load(self.model_path, self.config_path)
            
            self.voice = await asyncio.to_thread(load_voice)
            
            if not self.voice:
                raise Exception("Failed to load Piper voice")
                
            self.is_available = True
            logger.info("✅ Piper TTS initialized successfully")
            
        except Exception as e:
            logger.error(f"Failed to initialize Piper TTS: {e}")
            logger.info("Make sure to download the model files during build")
            self.is_available = False

    async def generate_speech_stream(self, text: str, speed: float = 1.0) -> AsyncGenerator[bytes, None]:
        """
        Generate streaming TTS audio for WebSocketHandler
        
        Args:
            text: Text to convert to speech
            speed: Speech speed multiplier
            
        Yields:
            Audio chunks in WAV format
        """
        try:
            if not self.is_available:
                logger.warning("TTS service not available")
                return
                
            if not text or not text.strip():
                logger.warning("Empty text provided for TTS")
                return
                
            self.is_speaking = True
            self.should_stop = False
            
            logger.info(f"TTS streaming: '{text[:50]}...'")
            
            # Generate speech using Piper
            def synthesize():
                return self.voice.synthesize(text, length_scale=1.0/speed)
            
            audio_samples = await asyncio.to_thread(synthesize)
            
            if audio_samples is None or len(audio_samples) == 0:
                logger.error("No audio data generated by Piper")
                return
            
            # Convert to WAV format
            def convert_to_wav():
                audio_bytes = io.BytesIO()
                sf.write(audio_bytes, audio_samples, self.sample_rate, format='WAV')
                return audio_bytes.getvalue()
            
            audio_data = await asyncio.to_thread(convert_to_wav)
            
            # Stream audio in chunks
            chunk_size = 4096  # 4KB chunks
            for i in range(0, len(audio_data), chunk_size):
                if self.should_stop:
                    logger.info("TTS streaming stopped")
                    break
                    
                chunk = audio_data[i:i + chunk_size]
                yield chunk
                
                # Small delay to simulate streaming
                await asyncio.sleep(0.01)
                
        except Exception as e:
            logger.error(f"TTS streaming error: {e}")
        finally:
            self.is_speaking = False

    async def stop(self):
        """Stop current TTS generation"""
        try:
            self.should_stop = True
            self.is_speaking = False
            logger.debug("TTS stopped")
        except Exception as e:
            logger.error(f"TTS stop error: {e}")
    
    async def synthesize_speech(self, text: str, speed: float = 1.0) -> Dict[str, Any]:
        """
        Convert text to speech using Piper TTS
        
        Args:
            text: Text to convert to speech
            speed: Speech speed multiplier (1.0 = normal speed)
            
        Returns:
            Dict with audio data and metadata
        """
        if not self.is_available:
            logger.warning("TTS service not available")
            return {
                "audio_data": None,
                "format": "wav",
                "sample_rate": self.sample_rate,
                "is_available": False,
                "error": "TTS service not configured"
            }
        
        if not text or not text.strip():
            logger.warning("Empty text provided for TTS")
            return {
                "audio_data": None,
                "format": "wav",
                "sample_rate": self.sample_rate,
                "is_available": True,
                "error": "Empty text"
            }
        
        try:
            logger.info(f"TTS synthesizing: '{text[:50]}...'")
            
            # Generate speech
            def synthesize():
                return self.voice.synthesize(text, length_scale=1.0/speed)
            
            audio_samples = await asyncio.to_thread(synthesize)
            
            if audio_samples is None or len(audio_samples) == 0:
                logger.error("No audio data generated by Piper")
                return {
                    "audio_data": None,
                    "format": "wav",
                    "sample_rate": self.sample_rate,
                    "is_available": True,
                    "error": "No audio data generated"
                }
            
            # Convert to bytes (WAV format)
            def convert_to_wav():
                audio_bytes = io.BytesIO()
                sf.write(audio_bytes, audio_samples, self.sample_rate, format='WAV')
                return audio_bytes.getvalue()
            
            audio_data = await asyncio.to_thread(convert_to_wav)
            
            logger.info(f"TTS generated {len(audio_data)} bytes of audio")
            
            return {
                "audio_data": audio_data,
                "format": "wav",
                "sample_rate": self.sample_rate,
                "text_length": len(text),
                "audio_size": len(audio_data),
                "duration": len(audio_samples) / self.sample_rate,
                "is_available": True
            }
            
        except Exception as e:
            logger.error(f"TTS synthesis failed: {e}")
            return {
                "audio_data": None,
                "format": "wav",
                "sample_rate": self.sample_rate,
                "is_available": True,
                "error": str(e)
            }
    
    async def synthesize_streaming(self, text: str, speed: float = 1.0, chunk_size: int = 4096) -> AsyncGenerator[bytes, None]:
        """
        Stream TTS audio in chunks for low-latency playback
        
        Args:
            text: Text to convert to speech
            speed: Speech speed multiplier
            chunk_size: Size of audio chunks to yield
            
        Yields:
            Audio chunks in WAV format
        """
        result = await self.synthesize_speech(text, speed)
        
        if result.get("audio_data"):
            audio_data = result["audio_data"]
            
            # Skip WAV header (44 bytes) for streaming
            wav_header = audio_data[:44]
            audio_content = audio_data[44:]
            
            # Yield header first
            yield wav_header
            
            # Stream audio content in chunks
            for i in range(0, len(audio_content), chunk_size):
                chunk = audio_content[i:i + chunk_size]
                yield chunk
                # Small delay to simulate streaming
                await asyncio.sleep(0.01)
    
    async def convert_to_opus(self, wav_data: bytes) -> Optional[bytes]:
        """
        Convert WAV audio to Opus format for better streaming
        
        Args:
            wav_data: WAV audio data
            
        Returns:
            Opus-encoded audio data or None if conversion fails
        """
        try:
            # Use ffmpeg to convert WAV to Opus
            process = await asyncio.create_subprocess_exec(
                'ffmpeg', '-f', 'wav', '-i', 'pipe:0', 
                '-c:a', 'libopus', '-b:a', '32k', '-frame_duration', '20',
                '-f', 'opus', 'pipe:1',
                stdin=asyncio.subprocess.PIPE,
                stdout=asyncio.subprocess.PIPE,
                stderr=asyncio.subprocess.PIPE
            )
            
            stdout, stderr = await process.communicate(input=wav_data)
            
            if process.returncode == 0:
                logger.debug(f"Converted WAV to Opus: {len(wav_data)} -> {len(stdout)} bytes")
                return stdout
            else:
                logger.error(f"ffmpeg conversion failed: {stderr.decode()}")
                return None
                
        except Exception as e:
            logger.error(f"Opus conversion error: {e}")
            return None
    
    async def synthesize_opus_streaming(self, text: str, speed: float = 1.0) -> AsyncGenerator[bytes, None]:
        """
        Stream TTS audio as Opus-encoded chunks
        
        Args:
            text: Text to convert to speech
            speed: Speech speed multiplier
            
        Yields:
            Opus-encoded audio chunks
        """
        # First synthesize the complete audio
        result = await self.synthesize_speech(text, speed)
        
        if result.get("audio_data"):
            # Convert to Opus
            opus_data = await self.convert_to_opus(result["audio_data"])
            
            if opus_data:
                # Stream Opus data in chunks
                chunk_size = 960  # Opus frame size for 20ms at 48kHz
                for i in range(0, len(opus_data), chunk_size):
                    chunk = opus_data[i:i + chunk_size]
                    yield chunk
                    await asyncio.sleep(0.02)  # 20ms frame duration
    
    async def test_connection(self) -> bool:
        """Test TTS service"""
        if not self.is_available:
            return False
        
        try:
            result = await self.synthesize_speech("Hello, this is a test.")
            return not result.get("error")
        except Exception as e:
            logger.error(f"TTS connection test failed: {e}")
            return False
    
    def get_status(self) -> Dict[str, Any]:
        """Get TTS service status"""
        return {
            "available": self.is_available,
            "service": "Piper TTS" if self.is_available else "Not Available",
            "voice": self.voice_name,
            "sample_rate": self.sample_rate,
            "model_path": self.model_path,
            "streaming": True,
            "is_speaking": self.is_speaking
        } 