import os
import asyncio
import logging
import tempfile # Not used directly in this version, consider removing if not needed elsewhere
import subprocess
import json # Not used directly in this version
from typing import Optional, Dict, Any, AsyncGenerator
import numpy as np
import soundfile as sf
from piper import PiperVoice # Assuming piper-tts is installed and provides this
import io

logger = logging.getLogger(__name__)

class TTSService:
    """Text-to-Speech service using Piper TTS with en_US-libritts-high model"""
    
    def __init__(self):
        self.voice: Optional[PiperVoice] = None
        self.is_available = False
        self.sample_rate = 22050  # Piper model's native sample rate
        self.target_sample_rate = 16000 # Target sample rate for consistency, if resampling is added
        self.model_path: Optional[str] = None
        self.config_path: Optional[str] = None
        
        self.model_dir = os.getenv("MODEL_PATH", "/app/models")
        self.voice_name = "en_US-libritts-high" # Example voice
        
        self.is_speaking = False # Indicates if TTS synthesis is active
        self.should_stop = False # Flag to interrupt ongoing synthesis
        
    async def initialize(self):
        """Initialize the Piper TTS model"""
        try:
            logger.info(f"Initializing Piper TTS with {self.voice_name} model...")
            
            self.model_path = os.path.join(self.model_dir, f"{self.voice_name}.onnx")
            self.config_path = os.path.join(self.model_dir, f"{self.voice_name}.onnx.json")
            
            if not os.path.exists(self.model_path):
                raise FileNotFoundError(f"Model file not found: {self.model_path}")
            if not os.path.exists(self.config_path):
                raise FileNotFoundError(f"Config file not found: {self.config_path}")
            
            def load_voice_sync(): # Synchronous part for asyncio.to_thread
                return PiperVoice.load(self.model_path, self.config_path) # type: ignore
            
            self.voice = await asyncio.to_thread(load_voice_sync)
            
            if not self.voice:
                raise Exception("Failed to load Piper voice model.")
                
            self.is_available = True
            logger.info(f"✅ Piper TTS ({self.voice_name}) initialized successfully. Native sample rate: {self.sample_rate}Hz.")
            
        except Exception as e:
            logger.error(f"Failed to initialize Piper TTS: {e}", exc_info=True)
            self.is_available = False
            # Optionally, explain where to get models if they are missing.
            if isinstance(e, FileNotFoundError):
                logger.info("Please ensure TTS models are downloaded via 'python -m app.models.download_models' or available at the configured MODEL_PATH.")

    async def generate_speech_stream(self, text: str, speed: float = 1.0) -> AsyncGenerator[bytes, None]:
        """
        Generate TTS audio for the given text and yield it as a single, complete audio buffer (WAV format).
        This approach prioritizes smooth playback on the frontend.
        """
        if not self.is_available or not self.voice:
            logger.warning("TTS service not available or voice not loaded, cannot generate speech.")
            return
        if not text or not text.strip():
            logger.warning("Empty text provided for TTS, skipping generation.")
            return
            
        self.is_speaking = True
        self.should_stop = False # Reset interruption flag for new request

        logger.info(f"TTS: Generating full audio for text: '{text[:70]}...' (Speed: {speed}x)")
        
        try:
            # Synchronous synthesis part
            def synthesize_sync():
                # Piper's synthesize method is blocking
                return self.voice.synthesize(text, length_scale=(1.0 / speed if speed > 0 else 1.0))

            audio_samples_np: Optional[np.ndarray] = await asyncio.to_thread(synthesize_sync)

            if self.should_stop:
                logger.info("TTS synthesis was interrupted.")
                self.is_speaking = False
                return

            if audio_samples_np is None or audio_samples_np.size == 0:
                logger.error("No audio samples generated by Piper TTS.")
                self.is_speaking = False
                return
            
            logger.debug(f"Piper generated {len(audio_samples_np)} audio samples at {self.sample_rate}Hz.")

            # Convert numpy array (float32) to WAV bytes in memory
            # Piper samples are typically float32. sf.write handles conversion.
            wav_buffer = io.BytesIO()
            
            # Synchronous soundfile write part
            def write_wav_sync():
                sf.write(wav_buffer, audio_samples_np, self.sample_rate, format='WAV', subtype='PCM_16')
                return wav_buffer.getvalue()

            audio_data_wav: bytes = await asyncio.to_thread(write_wav_sync)
            
            if self.should_stop:
                logger.info("TTS WAV conversion was interrupted.")
                self.is_speaking = False
                return

            if audio_data_wav:
                logger.info(f"TTS: Successfully generated {len(audio_data_wav)} bytes of WAV audio.")
                yield audio_data_wav # Yield the complete WAV audio data
            else:
                logger.error("TTS: Failed to convert synthesized samples to WAV format.")
                
        except Exception as e:
            logger.error(f"Error during TTS speech generation or WAV conversion: {e}", exc_info=True)
        finally:
            self.is_speaking = False # Ensure this is reset

    async def stop(self):
        """Signal to stop any ongoing TTS generation."""
        logger.debug("TTS stop signaled.")
        self.should_stop = True
        # Note: Piper's C library might not support immediate interruption of an ongoing synthesis.
        # This flag primarily prevents further processing or sending of audio chunks.
        # If piper runs in a subprocess (as in one of the original files), that subprocess could be terminated.
        # Here, with direct library calls, we rely on checking `should_stop` at key points.
        self.is_speaking = False # Immediately reflect that we intend to stop speaking

    # ... (synthesize_speech, synthesize_streaming, convert_to_opus, etc. can remain for other uses or be refactored)
    # For WebSocket streaming, generate_speech_stream is the key method.
    # The synthesize_speech method is still useful for non-streaming cases or testing.

    async def synthesize_speech(self, text: str, speed: float = 1.0) -> Dict[str, Any]:
        """
        Convert text to speech (complete, non-streaming) using Piper TTS.
        Returns WAV audio data.
        """
        if not self.is_available or not self.voice:
            logger.warning("TTS service not available for synthesize_speech.")
            return {"audio_data": None, "error": "TTS service not configured or voice not loaded"}
        # ... (rest of implementation is similar to the single yield in generate_speech_stream) ...
        logger.info(f"TTS (blocking): Synthesizing '{text[:50]}...'")
        try:
            def synthesize_sync():
                return self.voice.synthesize(text, length_scale=(1.0 / speed if speed > 0 else 1.0))
            audio_samples_np = await asyncio.to_thread(synthesize_sync)

            if audio_samples_np is None or audio_samples_np.size == 0:
                return {"audio_data": None, "error": "No audio data generated"}

            wav_buffer = io.BytesIO()
            def write_wav_sync():
                sf.write(wav_buffer, audio_samples_np, self.sample_rate, format='WAV', subtype='PCM_16')
                return wav_buffer.getvalue()
            audio_data = await asyncio.to_thread(write_wav_sync)
            
            duration = len(audio_samples_np) / self.sample_rate
            return {
                "audio_data": audio_data,
                "format": "wav",
                "sample_rate": self.sample_rate, # Piper's native rate
                "duration": duration,
                "text_length": len(text),
                "is_available": True
            }
        except Exception as e:
            logger.error(f"TTS synthesis_speech failed: {e}", exc_info=True)
            return {"audio_data": None, "error": str(e)}


    def get_status(self) -> Dict[str, Any]:
        """Get TTS service status"""
        return {
            "available": self.is_available,
            "service_type": "Piper_TTS",
            "voice_model": self.voice_name,
            "model_native_sample_rate": self.sample_rate,
            "is_currently_speaking": self.is_speaking
        }

    async def cleanup(self):
        """Clean up TTS resources"""
        logger.info("Cleaning up TTS service...")
        await self.stop() # Ensure any synthesis is signaled to stop
        if self.voice:
            # PiperVoice object does not have an explicit close or cleanup method in its Python bindings
            # Rely on Python's garbage collection for the underlying C resources if not managed otherwise
            self.voice = None 
        self.is_available = False
        logger.info("TTS service cleaned up.")